#!/usr/bin/env bash
# transfers a file from our client to a server
# Accepts four parameters
#    1. The path to the file to be transferred
#    2. The IP of the server to transfer the file to
#    3. The username that scp connects with
#    4. The path to the SSH private key that scp uses

# ARGUMENT CONVENTION
# $1 - PATH_TO_FILE
# $2 - IP
# $3 - USERNAME
# $4 - PATH_TO_SSH_KEY

if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ $# -eq 3 ]; then
    scp -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
fi